"""Fixed limits for the TTS component."""

import re
from pathlib import Path

MAX_INPUT_TEXT_CHARS = 1_000_000
MAX_HTTP_TEXT_BYTES = 6 * 1024 * 1024

HARD_TEXT_SEGMENT_CAP = 512
MAX_EMITTED_AUDIO_CHUNKS = 8

PROGRESS_TIMEOUT_SECONDS = 60
TOTAL_UPLOAD_TIMEOUT_SECONDS = 60
WORKER_KILL_AFTER_SECONDS = 5.0
MAX_PCM_CHUNK_BYTES = 4 * 1024 * 1024

MAX_CUSTOM_VOICES = 64
MAX_VOICE_UPLOAD_BYTES = 10 * 1024 * 1024
MAX_TOTAL_CUSTOM_VOICE_BYTES = 100 * 1024 * 1024
MAX_VOICE_STATE_BYTES = 64 * 1024 * 1024
VOICE_STATE_BUILD_TIMEOUT_SECONDS = 30

MIN_SPEED = 0.25
MAX_SPEED = 4.0
DEFAULT_SPEED = 1.0

PCM_SAMPLE_RATE = 24_000
PCM_CHANNELS = 1
PCM_SAMPLE_WIDTH_BYTES = 2

SENTENCE_BOUNDARY_PAUSE_MS = 400
CLAUSE_BOUNDARY_PAUSE_MS = 200
BOUNDARY_PAUSE_JITTER_MIN = 0.9
BOUNDARY_PAUSE_JITTER_MAX = 1.1
SEGMENT_FADE_IN_MS = 10
SEGMENT_FADE_EXPONENT = 4.0

TARGET_TTS_TOKENS = 100

PARAGRAPH_SPLIT_RE = re.compile(r"\n\s*\n+")
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")
PUNCTUATION_SPLIT_RE = re.compile(r"(?<=[^\w\s])\s+")
LONG_TOKEN_RE = re.compile(r"\S{51,}")
LONG_TOKEN_PLACEHOLDER = "too-long-word-skipped"
INTER_SEGMENT_LEADIN = "  "

VOICE_STATE_SUFFIX = ".safetensors"
LEGACY_VOICE_STATE_SUFFIX = ".state"

VOICE_STORE_ROOT = Path.home() / ".trillim" / "voices"
VOICE_MANIFEST_NAME = "manifest.json"
