"""Fixed internal limits for the STT component."""

from __future__ import annotations

MAX_UPLOAD_BYTES = 64 * 1024 * 1024
PCM_WIDTH_BYTES = 2
PCM_CHANNELS = 1
PCM_SAMPLE_RATE = 16000
UPLOAD_PROGRESS_TIMEOUT_SECONDS = 15
TOTAL_UPLOAD_TIMEOUT_SECONDS = 300
TOTAL_TRANSCRIPTION_TIMEOUT_SECONDS = 180
WORKER_KILL_AFTER_SECONDS = 5.0
MAX_WORKER_OUTPUT_BYTES = 4 * 1024 * 1024
MAX_LANGUAGE_CHARS = 32
STARTUP_TIMEOUT_SECONDS = 30.0
