"""Fixed internal limits for the STT component."""

from __future__ import annotations

MAX_ACTIVE_TRANSCRIPTIONS = 1
MAX_QUEUED_TRANSCRIPTIONS = 0
MAX_UPLOAD_BYTES = 64 * 1024 * 1024
TOTAL_TRANSCRIPTION_TIMEOUT_SECONDS = 180
WORKER_KILL_AFTER_SECONDS = 1.0
SPOOL_CHUNK_SIZE_BYTES = 64 * 1024
MAX_LANGUAGE_CHARS = 32
